networks:
  nrv.net:
    driver: bridge

services:
  api.nrv:
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    env_file: nrv.env
    ports:
      - '48013:80'
    volumes:
      - ./app:/var/php
    working_dir: /var/php
    networks:
      - nrv.net
    depends_on:
      - nrv.db
    command: php -S 0.0.0.0:80 -t /var/php/public

  nrv.db:
    image: 'postgres:latest'
    env_file: nrvdb.env
    ports:
      - '48011:5432'
    networks:
      - nrv.net
    volumes:
      - ./app/sql:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - '48012:8080'
    networks:
      - nrv.net
    command: php -S 0.0.0.0:8080 -t /var/www/html

  front.nrv:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "48010:48010"
    volumes:
      - ./Frontend:/usr/src/app/Frontend
      - /usr/src/app/Frontend/node_modules
    environment:
      - NODE_ENV=development
      - PORT=48010
    networks:
      - nrv.net
    depends_on:
      - api.nrv
    command: >
      sh -c "npm run build &&
             npm run dev"