networks:
  nrv.net:
    driver: bridge

services:
  api.nrv:
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    env_file: nrv.env
    ports:
      - '7080:80'
    volumes:
      - ./app:/var/php
    working_dir: /var/php
    networks:
      - nrv.net
    depends_on:
      - nrv.db
    command: php -S 0.0.0.0:80 -t /var/php/public

  nrv.db:
    image: 'postgres:latest'
    env_file: nrvdb.env
    ports:
      - '5433:5432'
    networks:
      - nrv.net
    volumes:
      - ./app/sql:/var/sql

  adminer:
    image: adminer
    ports:
      - '8081:8080'
    networks:
      - nrv.net

  front.nrv:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./Frontend:/usr/src/app/Frontend
      - /usr/src/app/Frontend/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - nrv.net
    depends_on:
      - api.nrv
    command: npm run dev